### PR TITLE
Feature: Use dry-types for coercion

### PR DESCRIPTION
**Pull request by mrbongiolo**
Using `dry-types` instead of `virtus` for coercion.

Everything seems fine.

### CODE REVIEW

**Comment by mrbongiolo** [comment]
Does we still need to support ruby 1.9.3?

**Comment by blelump** [comment]
It seems `dry-eq` [is not](https://github.com/dry-rb/dry-equalizer#supported-ruby-versions) compatible with 1.9.3 so we cannot meet the dependency requirement.

**Comment by apotonick** [comment]
This is great, but I would love to support 1.9. The TRB gems are supposed to help people get out of their mess, which often means they're still on 1.9...?

**Comment by apotonick** [comment]
Maybe we can make Reform 2.2 >= 2.0 ?

**Comment by mrbongiolo** [comment]
@apotonick It's fine for me. Make it a major bump. If people are using 1.9 they can stay on disposable with Virtus. whenever they upgrade they might get the new version then.

**Comment by apotonick** [comment]
Good idea.

Hey, @mrbongiolo, can you find out how we could have the "nilify" feature? As in, when an empty/blank string comes in, that's coerced into `nil`? Many have asked for it.

**Pull request merged**
